### ISSUE TITLE
Missing example, please provide

### ISSUE THREAD

**Issue by tszebeni** [googleapis/python-private-catalog#39]
The python client documentation is kind of useless if you would like to see an example code, not method signature what IDEs are usually already helps with.
Please provide an example code, similar to the nodejs version of this api where the example already can be seen on readme file. That provides much help with little effort.
Thanks

**Comment by busunkim96** [comment]
Hi @tszebeni,

Thank you for the feedback. We are working on integrating code examples into the docstrings. For now, I've enabled autogenerated code snippets on this repository. You can see the output in this branch: https://github.com/googleapis/python-private-catalog/tree/snippetgen-with-request-args/samples/generated_samples

The imports, client initialization, and method call should work as-is. You will need to modify the request arguments. The docstring for each `...Request` class explains how each attribute should be initialized. Only attributes marked `required` are required, everything else is optional.

https://github.com/googleapis/python-private-catalog/blob/450ced05bef161a42013d3c44bf5a955d869f899/samples/generated_samples/cloudprivatecatalog_generated_privatecatalog_v1beta1_private_catalog_search_versions_sync.py#L27-L46

https://github.com/googleapis/python-private-catalog/blob/961d3e0c875f0967a4085151f767223f6db67d55/google/cloud/privatecatalog_v1beta1/types/private_catalog.py#L151-L181

**Comment by parthea** [comment]
Sample code snippets are now included in individual docstrings as well as in the generated_samples directory here: https://github.com/googleapis/python-private-catalog/tree/main/samples/generated_samples .
